[workspace]
resolver = "2"
members = ["dbopen","lib", "migration", "migration-runner"]

[package]
name = "dx_todo_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "*"
hot-lib-reloader = "^0.7.0"
lib = { path = "lib", features = ["migration"]}
log = "*"
poem = { workspace = true, features = ["compression"]}
dotenvy = { workspace = true }
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
dbopen = { workspace = true }
sea-orm = { workspace = true, features = [
    "sea-orm-internal"
] }

[workspace.dependencies]
poem = { version = "^3.0.1" }
poem-grants = { version ="^3.0.0" }
poem-openapi = { version = "^5.0.2" }
dotenvy = { version = "^0.15.7" }
tokio = "^1.37.0"
anyhow = { version = "1.0.86", features = ["backtrace"] }
dbsession = { git = "https://github.com/887/dbsession.git", default-features = true }
sea-orm = { version = "^0.12.15" }
dbopen = { path = "dbopen", default-features = false }
migration = { path = "migration", default-features = false }
migration-runner = { path = "migration-runner", default-features = false }

[features]
default = ["sqlite-rustls"]
path-info = []
mysql-rustls = ["lib/mysql-rustls", "dbopen/mysql-rustls"]
mysql-native-tls = ["lib/mysql-native-tls", "dbopen/mysql-native-tls"]
sqlite-rustls = ["lib/sqlite-rustls", "dbopen/sqlite-rustls"]
sqlite-native-tls = ["lib/sqlite-native-tls", "dbopen/sqlite-native-tls"]
posgres-rustls = ["lib/posgres-rustls", "dbopen/posgres-rustls"]
posgres-native-tls = ["lib/posgres-native-tls", "dbopen/posgres-native-tls"]
