[workspace]
resolver = "2"
members = ["dbopen","lib", "migration", "migration-runner"]

[package]
name = "dx_todo_backend"
version = "0.1.0"
edition = "2021"

[profile.dev]
codegen-backend = "cranelift"

[dependencies]
#env_logger = "*"
hot-lib-reloader = { version = "^0.7.0", optional = true }
lib = { path = "lib", default-features = false }
dotenvy = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
migration-runner = { workspace = true, optional = true }

[workspace.dependencies]
poem = { version = "^3.0.1" }
poem-grants = { version ="^3.0.0" }
poem-openapi = { version = "^5.0.2" }
dotenvy = { version = "^0.15.7" }
tokio = { version = "^1.37.0", default-features = false }
anyhow = { version = "1.0.86", features = ["backtrace"] }
dbsession = { git = "https://github.com/887/dbsession.git", default-features = true }
sea-orm = { version = "^0.12.15", default-features = false }
dbopen = { path = "dbopen", default-features = false }
migration = { path = "migration", default-features = false }
migration-runner = { path = "migration-runner", default-features = false }
base64 = "0.22.1"

[features]
default = ["sqlite-rustls", "migration", "hot-reload"]
path-info = []
hot-reload = ["dep:hot-lib-reloader", "migration-runner/hot-reload", "lib/hot-reload"]
migration = ["dep:migration-runner"]
mysql-rustls = ["lib/mysql-rustls", "migration-runner/mysql-rustls"]
mysql-native-tls = ["lib/mysql-native-tls", "migration-runner/mysql-native-tls"]
sqlite-rustls = ["lib/sqlite-rustls", "migration-runner/sqlite-rustls"]
sqlite-native-tls = ["lib/sqlite-native-tls", "migration-runner/sqlite-native-tls"]
postgres-rustls = ["lib/postgres-rustls", "migration-runner/postgres-rustls"]
postgres-native-tls = ["lib/postgres-native-tls", "migration-runner/postgres-native-tls"]
